config/routes.rb
Rails.application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#new"

  resources :home
  resources :users
  resources :sessions
  resources :search

end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessor :email, :password, :password_confirmation

  # before_save :encrypt_password
  has_secure_password

  # validates_confirmation_of :password
  # validates_presence_of :password, :on => :create
  # validates_presence_of :email
  # validates_uniqueness_of :email

  # def self.authenticate(email, password)
  #   user = find_by_email(email)
  #   if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
  #     user
  #   else
  #     nil
  #   end
  # end

  def self.authenticate(email, password)
    user = find_by_email(email)
    return user
  end

  # def encrypt_password
  #   if password.present?
  #     self.password_salt = BCrypt::Engine.generate_salt
  #     self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end


end

app/controllers/home_controller.rb
require 'httparty'
# require 'flickr'
class HomeController < ApplicationController

  def index
    # Call http://api.theysaidso.com/qod.json and get JSON response
    response = HTTParty.get('http://api.forismatic.com/api/1.0/?method=getQuote&key=457653&format=json&lang=en')

    # Quote to show is inside response.contents.quote
    @quoteStr = response['quoteText']

   # @flickr_api= '1f012f3e9cc5b28d42ebfe203097107f'
   # @flickr_secret='761c7a82a443a6bc'

   # flickr = Flickr.new(@flickr_api)
   # params = Hash.new()
   # params[:safe_search] = 3
   # params[:format] = "json"
   # params[:tags] = "moon"

   # photos = flickr.photos_search(params)
   # # $stdout.puts(photos)
  end

  def show
  end

end

app/controllers/search_controller.rb
require 'google/api_client'

class SearchController < ApplicationController


  def index
  end

  def create
    # Set DEVELOPER_KEY to the "API key" value from the "Access" tab of the
    # Google Developers Console <https://cloud.google.com/console>
    # Please ensure that you have enabled the YouTube Data API for your project.
    @DEVELOPER_KEY = "AIzaSyC2hdsVP2yOwodJ5a1iaetvmf0zrz4yeGo"
    @YOUTUBE_API_SERVICE_NAME = "youtube"
    @YOUTUBE_API_VERSION = "v3"

    client = Google::APIClient.new(:key => @DEVELOPER_KEY,
                                   :authorization => nil)
    youtube = client.discovered_api(@YOUTUBE_API_SERVICE_NAME, @YOUTUBE_API_VERSION)

    # Call the search.list method to retrieve results matching the specified
    # query term.
    opts = Hash.new
    opts[:part] = 'id,snippet'
    opts[:q] = params[:query]
    opts[:safeSearch]='strict'
    search_response = client.execute!(
      :api_method => youtube.search.list,
      :parameters => opts
    )

    @videos = []

    $stdout.print(search_response.data)
    # Add each result to the appropriate list, and then display the lists of
    # matching videos, channels, and playlists.
    search_response.data.items.each do |search_result|
      case search_result.id.kind
        when 'youtube#video'
          @videos.push("#{search_result.id.videoId}")
      end
    end

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end


  def create
    $message = nil
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to "/home"
    else
      $message= "Invalid email or password"
      redirect_to 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


def new
  @user = User.new
end


def show
 @user = User.find(params[:id])
end

def create
  # binding.pry
  @user = User.new user_params
  if @user.save
    redirect_to root_url, :notice => "Signed up!"
  else
    render "new"
  end
end

private

def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<head>

  <title>layout one</title>
  <link href="css/bootstrap.min.css" rel="stylesheet">
  <link href="css/bootstrap-theme.min.css" rel="stylesheet">
  <link href="css/bootstrap.css" rel="stylesheet">
  <link rel="stylesheet" href="./one.css">

</head>

<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <!--
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>-->
      <a class="navbar-brand">SANDBOX</a>
    </div>
    <!--
    <div id="navbar" class="collapse navbar-collapse">
    <ul class="nav navbar-nav navbar-right">
    <li><a href="#about">About</a></li>
    <li><a href="#contact">Contact</a></li>
  </ul>
</div>
-->
  <title>SANBOX</title>
  <!--
<<<<<<< HEAD
  <link rel="stylesheet" href="./one.css"> -->
  <link href="bootstrap-theme.min.css" rel="stylesheet">
  <link href="bootstrap.min.css" rel="stylesheet">
  <link href="bootstrap.css" rel="stylesheet">



  <link rel="stylesheet" href="two.css">


<div class="welcome">
  <h2>Welcome to SandBox</h2>
  <p><%= @quoteStr %></p><br/>
</div>

<div class="row">
  <div class="container">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="col-md-1"></div>
        <div class="col-md-10" id="form">
<!--           <form method="POST" action="search">
            <label>Search:</label>
            <input type="text" name="search_term" placeholder="what are you searching for?" id="field" required>
            &nbsp;
            <label>Safe search?</label>
            &nbsp;
            <input type="checkbox" name="safe_search">
            &nbsp;
            &nbsp;
            <button class="btn waves-effect waves-light" type="submit" name="action">Submit
              <i class="mdi-content-send right"></i>
            </button>
            <div class="col-md-1"></div>
          </form> -->

          <%= form_tag "/search" do %>
            <%= label_tag :Search_YOUTUBE_Content%><br/>
            <%= text_field_tag :query %>
            <br/>
            <br/>

            <%= submit_tag "Search" %>
          <% end %>
          </div>

        </div>
</head>

<body>
  <nav class="navbar navbar-fixed-top" id="nav">
    <div class="container">
      <div class="navbar-header">

        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#top" id="name">SANDBOX</a>

      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#"><span class="glyphicon glyphicon-th"></span></a></li>
          <li><a href="#"><span class="glyphicon glyphicon-lock"></span></a></li>
          <li><a href="#"><span class="glyphicon glyphicon-cog"></span></i></a></li>
        </ul>
      </div>
    </div>
  </nav>

  <a name="top"></a>

  <div class="row">
    <div class="container" id="greeting">
      <div class="col-md-5">

        <h1>Hi Input... (<a href="/log_out">logout</a>)</h1>
        <br />
        <p class="lead"><%= @quoteStr %></p>
        <div id="find">
          <form id="cse-search-box" action="http://www.google.com/cse">
            <input id="search" type="text" name="q">
            <input id="submit" type="submit" value="Search">
            <input type="hidden" name="cx" value="013474379445953100237:sx5yuk89gso">
            <input type="hidden" name="safe" value="active">
            <input type="hidden" name="ie" value="UTF-8">
          </form>
        </div><!--find-->
      </div><!--col-md-5-->
    </div><!--greeting-->
    <div class="container">
    <div class="col-md-3">
      &nbsp;
    </div>
  </div>

</div>

<div id="videoContainer">
  <div id="map">
  </div>
</div>

  <div class="container">
    <div class="col-md-4">
      <div id="player"></div>
    </div>

  </div>
  </div><!--row-->

  <!--
  <div class="row">
  <div class="container">
  <div class="panel panel-default">
  <div class="panel-body">
  <div class="col-md-1"></div>
  <div class="col-md-10" id="form">-->
  <!--           <form method="POST" action="search">
  <label>Search:</label>
  <input type="text" name="search_term" placeholder="what are you searching for?" id="field" required>
  &nbsp;
  <label>Safe search?</label>
  &nbsp;
  <input type="checkbox" name="safe_search">
  &nbsp;
  &nbsp;
  <button class="btn waves-effect waves-light" type="submit" name="action">Submit
  <i class="mdi-content-send right"></i>
</button>
<div class="col-md-1"></div>
</form> -->
<!--
<%= form_tag "/search" do %>
<%= label_tag :query %><br/>
<%= text_field_tag :query %>
<br/>
<br/>

<%= submit_tag "Search" %>
<% end %>
</div>



<!-- <div class="row">

</div>
</div>
</div>
</div>
</div> -->

<div class="row">

  <div class="container" id="columns">
    <div class="col-md-4">
      <div class="img-responsive">
      <%= image_tag "explore.png" %>
    </div>
    </div>
    <div class="col-md-4">
      <%= image_tag "play.png" %>
    </div>
    <div class="col-md-4">
      <%= image_tag "favsites.png" %>
    </div>

  </div>
</div> -->

  </div><!--columns-->
</div><!--row-->


<script>
// 2. This code loads the IFrame Player API code asynchronously.
var tag = document.createElement('script');

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName('script')[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

// 3. This function creates an <iframe> (and YouTube player)
//    after the API code downloads.
var player;
function onYouTubeIframeAPIReady() {
  player = new YT.Player('player', {
    height: '290',
    width: '540',
    videoId: 'CgJKLhQMVzk',
    events: {
      'onReady': onPlayerReady,
      'onStateChange': onPlayerStateChange
    }
  });
}

// 4. The API will call this function when the video player is ready.
function onPlayerReady(event) {
  event.target.playVideo();
}

// 5. The API calls this function when the player's state changes.
//    The function indicates that when playing a video (state=1),
//    the player should play for six seconds and then stop.
var done = false;
function onPlayerStateChange(event) {
  if (event.data == YT.PlayerState.PLAYING && !done) {
    setTimeout(stopVideo, 6000);
    done = true;
  }
}
function stopVideo() {
  player.stopVideo();
}
</script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<header>
  <header>

<head>
  <title>Safe Search Engine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/0.4.2/sweet-alert.css"> -->
  <%= csrf_meta_tags %>
</head>


  <head>
    <title>Safe Search Engine</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' =>true %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/0.4.2/sweet-alert.css">
    <%= csrf_meta_tags %>
  </head>

  <body>

  <%= yield %>

  <div id="user_nav">
    <% if current_user %>
      Logged in as <%= current_user.email %>.
      <%= link_to "Log out", log_out_path %>
    <% else %>
      <div id="links"><%= link_to "Sign up", sign_up_path %> or
      <%= link_to "log in", log_in_path %>
    <% end %>
  </div>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>

  </body>

</html>

app/views/search/create.html.erb
<ul>

<% @videos.each do |videoID| %>
  <li><iframe width="420" height="315" src="https://www.youtube.com/embed/<%= videoID %>" frameborder="0" allowfullscreen></iframe></li>
<% end %>

</ul>

app/views/search/new.html.erb
<!--
<h1>Register:</h1>
<#%= form_for @user do |f| %>
  <#%= f.text_field :name %><br>
  <#%= f.label :email, "Email" %>:
  <#%= f.text_field :email %><br>
  <#%= f.label :password, "Password" %>:
  <#%= f.password_field :password %><br>
  <#%= f.submit %>
<#% end %>
 -->
<h1>Sign Up</h1>


<p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/new.html.erb
<div class="register">
<h3>Register for Sandbox</h3>

<%= form_for @user do |f| %>
  <%= f.label :name, "Name" %>:
  <%= f.text_field :name %><br>
  <%= f.label :email, "Email" %>:
  <%= f.text_field :email %><br>
  <%= f.label :password, "Password" %>:
  <%= f.password_field :password %><br>
  <%= f.submit %>

<% end %>

</div>

app/views/users/show.html.erb
<h1><% @user.name %></h1>
<br />
<h3><% @user.email %></h3>
<br />